//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCFG.Models.OCFG_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Association
    {
        public int id { get; set; }
        public int resgistry_code { get; set; }
        public string name { get; set; }
        public string region { get; set; }
        public string canton { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ConcreteLiquidation ConcreteLiquidation { get; set; }
        public virtual EconomicReport EconomicReport { get; set; }
        public virtual Settlement Settlement { get; set; }
        public virtual WorkPlan WorkPlan { get; set; }
    }
}
