//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCFG.Models.OCFG_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int id_manager { get; set; }
        public string user_name { get; set; }
        public string password_manager { get; set; }
        public int id_employee { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
