//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCFG.Models.OCFG_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OCFG_DataBaseEntities : DbContext
    {
        public OCFG_DataBaseEntities()
            : base("name=OCFG_DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Association> Association { get; set; }
        public virtual DbSet<ConcreteLiquidation> ConcreteLiquidation { get; set; }
        public virtual DbSet<EconomicReport> EconomicReport { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Officer> Officer { get; set; }
        public virtual DbSet<Settlement> Settlement { get; set; }
        public virtual DbSet<WorkPlan> WorkPlan { get; set; }
    }
}
