//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCFG.Models.OCFG_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPlan
    {
        public int id { get; set; }
        public System.DateTime assembly_date { get; set; }
        public string status { get; set; }
    
        public virtual Association Association { get; set; }
    }
}
